pipeline {
    agent any
    tools{
        jdk 'JDK17'
        maven 'maven_build'
    }
    environment{
        SCANNER_HOME = tool 'sonarscanner'
    }
    
    stages {
        stage('git-checkout') {
            steps {
                git 'https://github.com/lucky1416/java_practice.git'
            }
        }

        stage('Code-Compile') {
            steps {
                sh "mvn clean compile"
            }
        }

        stage('Unit-Test') {
            steps {
                sh "mvn clean test"
            }
        }
    }
}
